apiVersion: v1
kind: Service
metadata:
        #creationTimestamp: "2019-09-25T20:32:52Z"
  labels:
    run: client
  name: client-lb
  namespace: default
  #resourceVersion: "29987"
  #selfLink: /api/v1/namespaces/default/services/client-lb
  #uid: a5c8a092-dfd3-11e9-974c-42010a80011e
spec:
        #clusterIP: 10.12.13.29
        #externalTrafficPolicy: Cluster
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    run: client
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer: {}
