apiVersion: v1
kind: Service
metadata:
        #labels:
          #run: server
  name: server-lb
  # namespace: default
  #resourceVersion: "30075"
  #selfLink: /api/v1/namespaces/default/services/server-lb
  #uid: b50e3374-dfd3-11e9-974c-42010a80011e
spec:
        #clusterIP: 10.12.0.122
        #externalTrafficPolicy: Cluster
  ports:
  - port: 8082
    protocol: TCP
    targetPort: 8082
  selector:
    run: server
  type: ClusterIP
    #status:
        #loadBalancer: {}
